name: Main Orchestrator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Which type of version bump to perform (patch, minor, major)'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/build.yml

  call-bump:
    needs: call-build
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    uses: ./.github/workflows/bump-version.yml
    with:
      bump_type: ${{ github.event.inputs.bump_type || 'patch' }}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}